### ISSUE TITLE
Announcement Blurbs

### ISSUE THREAD

**Issue by Nickster28** [csbridge/turkey-21-website#10]
We've gone through and modified some of the announcement blurb text used throughout the course and displayed on the course homepage telling students important information.  We were hoping someone could look through the short announcement files and confirm the translations are up to date.  Here are the main announcement files we need to check:

+ `templates/announcements/tr/pre-program.ptl` should be a translation of `templates/announcements/en/pre-program.ptl`
+ `templates/announcements/tr/default.ptl` should be a translation of `templates/announcements/en/default.ptl`
+ `templates/announcements/tr/lecture.ptl` should be a translation of `templates/announcements/en/lecture.ptl`
+ `templates/announcements/tr/final-project-work-time` should be a translation of `templates/announcements/en/final-project-work-time.ptl`

**Comment by mertcoskunn** [comment]
I will work on this issue.
