### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by Nickster28** [csbridge/turkey-21-website#2]
The course summary text on the homepage needs to be updated with the names of the new schools collaborating on the course.  This is the following paragraph:

> The point of this three week course is to teach you the fundamentals of computer programming to the point where you can go and learn on your own. It is taught by a collaboration of instructors from Stanford University, Koç University, and Izmir Democracy University. You will learn to program using material from Stanford's Introduction to Computer Science course.

The english file is `templates/en/index.html` and the translation file is `templates/tr/index.html`.

**Comment by berravc1** [comment]
I will work on this issue.
