### ISSUE TITLE
Navigation Bar Updates

### ISSUE THREAD

**Issue by Nickster28** [csbridge/turkey-21-website#9]
There were a few new items added to the navigation bar that need to have Turkish translations added.  The file is `templates/parts/navBar.ptl`, and in that file all translations are added at the top.  Each line needs to have the English and Turkish equivalents - the following lines don't have a Turkish translation, and instead have the English version again:

- line 51 ("Sponsors")
- line 36 ("References")
- line 37 ("Software")
- line 40 ("Code of Conduct")

To add translations, change them to include the Turkish equivalent second, e.g.

```
translation_dictionary["Sponsors"] = {"en": "Sponsors", "tr": "YOUR TRANSLATION HERE"}
```

**Comment by ahmetuysal** [comment]
Cem Karbuz is working on this issue.
